# Generated by Django 2.2.5 on 2019-09-11 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group_invitation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='members',
        ),
    ]
