# Generated by Django 2.2.5 on 2019-09-11 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group_invitation', '0002_remove_group_members'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='values',
            new_name='group',
        ),
    ]
