# Generated by Django 2.2.5 on 2019-09-11 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_invitation', '0003_auto_20190911_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='groupId',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
