# Generated by Django 2.2.5 on 2019-09-14 16:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import group_invitation.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('group_invitation', '0005_auto_20190911_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='groupId',
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name='TeamInvitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp_created', models.DateTimeField(auto_now_add=True)),
                ('timestamp_updated', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254)),
                ('code', models.CharField(default=group_invitation.models.generate_invite_code, max_length=25)),
                ('status', models.IntegerField(choices=[(0, 'PENDING'), (1, 'ACCEPTED'), (2, 'DECLINED'), (4, 'EXPIRED')], default=0)),
                ('invited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitations_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'team invitation',
                'verbose_name_plural': 'team invitations',
                'unique_together': {('email', 'code')},
            },
        ),
    ]
