# Generated by Django 2.2.5 on 2019-09-15 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group_invitation', '0006_auto_20190914_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='teaminvitation',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='group_invite', to='group_invitation.Group'),
            preserve_default=False,
        ),
    ]
