# Generated by Django 2.2.5 on 2019-09-16 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_invitation', '0007_teaminvitation_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='capacity',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='group',
            name='searchable',
            field=models.BooleanField(default=True),
        ),
    ]
